### ISSUE TITLE
Difficulty loading plugin

### ISSUE THREAD

**Issue by AdamCampbell** [orta/cocoapods-expert-difficulty#2]
## Steps taken:
1. `bundle update cocoapods`
2. Added cocoapods-expert-difficulty to Gemfile
3. `bundle install`
4. Added plugin line to Podfile
5. `pod install`
## Output:

`````` ---------------------------------------------
Error loading the plugin with path `/Users/adamcampbell/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-expert-difficulty-1.0.0/lib/cocoapods_plugin.rb`.

ArgumentError - wrong number of arguments (2 for 1)
/Users/adamcampbell/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.35.0/lib/cocoapods/hooks_manager.rb:31:in `register'
/Users/adamcampbell/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-expert-difficulty-1.0.0/lib/cocoapods_plugin.rb:5:in `<module:CocoaPodsExpert>'
/Users/adamcampbell/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-expert-difficulty-1.0.0/lib/cocoapods_plugin.rb:3:in `<top (required)>'
/Users/adamcampbell/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.7.0/lib/claide/command/plugins_helper.rb:104:in `require'
/Users/adamcampbell/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.7.0/lib/claide/command/plugins_helper.rb:104:in `safe_require'
/Users/adamcampbell/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.7.0/lib/claide/command/plugins_helper.rb:32:in `block in load_plugins'
/Users/adamcampbell/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.7.0/lib/claide/command/plugins_helper.rb:31:in `each'
/Users/adamcampbell/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.7.0/lib/claide/command/plugins_helper.rb:31:in `load_plugins'
/Users/adamcampbell/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.7.0/lib/claide/command.rb:265:in `run'
/Users/adamcampbell/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:45:in `run'
/Users/adamcampbell/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.35.0/bin/pod:43:in `<top (required)>'
/Users/adamcampbell/.rbenv/versions/2.1.3/bin/pod:23:in `load'
/Users/adamcampbell/.rbenv/versions/2.1.3/bin/pod:23:in `<main>'
---------------------------------------------


[!] Invalid `Podfile` file: undefined method `plugin' for #<Pod::Podfile:0x007fca089913b0>. Updating CocoaPods might fix the issue.

 #  from /Users/adamcampbell/Development/project/Podfile:4
 #  -------------------------------------------
 #  
 >  plugin "cocoapods-expert-difficulty"
 #  
 #  -------------------------------------------```
``````

**Comment by orta** [comment]
You're using `cocoapods-0.35.0` when you do `pod install` - you need to use `bundle exec pod install` to use your Gemfile version :dancers:

**Comment by orta** [comment]
I've updated the README to help others who might be in the same position :100:

**Comment by AdamCampbell** [comment]
It wasn't that I wasn't using bundle exec, it was that I didn't update cocoapods :+1: 
Do I need to do anything after that? Or should it just work? I'm having issues with xcode not being able to find a specific framework now "file not found" errors (Although it autocompletes it fine).
This may be a separate issue though.

**Comment by orta** [comment]
Well, there are some frameworks that are _not_ on tvOS for example, so your pods may [need changing](https://github.com/artsy/Artsy-Authentication/pull/15) - regardless of the platform stuff.
